import { apiReference } from '../../generated/api-reference.generated';
import type { ApiReferenceData } from './api-reference.types';

/** Public references grouped by their playground route. */
export const apiReferences: Readonly<Record<string, readonly ApiReferenceData[]>> = {
  accordion: [apiReference.Accordion],
  'auto-focus': [apiReference.AutoFocus],
  autocomplete: [apiReference.Autocomplete],
  avatar: [apiReference.Avatar, apiReference.AvatarGroup],
  badge: [apiReference.Badge],
  button: [apiReference.Button],
  card: [apiReference.Card, apiReference.CardTitle, apiReference.CardMedia, apiReference.CardActions],
  checkbox: [apiReference.Checkbox],
  chip: [apiReference.Chip],
  code: [apiReference.Code, apiReference.CodeLine],
  'color-picker': [apiReference.ColorPicker],
  'data-view': [apiReference.DataView],
  divider: [apiReference.Divider],
  dialog: [
    apiReference.Dialog,
    apiReference.DialogTrigger,
    apiReference.DialogClose,
    apiReference.DialogHeader,
    apiReference.DialogBody,
    apiReference.DialogFooter,
  ],
  drawer: [
    apiReference.Drawer,
    apiReference.DrawerTrigger,
    apiReference.DrawerClose,
    apiReference.DrawerContent,
    apiReference.DrawerHeader,
    apiReference.DrawerFooter,
  ],
  fieldset: [apiReference.Fieldset, apiReference.FieldsetLegend, apiReference.FieldsetContent, apiReference.FieldsetToggle],
  'file-drop': [apiReference.FileDrop],
  'file-input': [apiReference.FileInput],
  indicator: [apiReference.Indicator, apiReference.IndicatorItem],
  input: [apiReference.Input],
  'input-group': [apiReference.InputGroup, apiReference.InputGroupAddon],
  'input-number': [apiReference.InputNumber],
  'input-otp': [apiReference.InputOtp],
  'input-surface': [apiReference.InputSurface, apiReference.InputSurfaceControl],
  join: [apiReference.Join, apiReference.JoinItem],
  kbd: [apiReference.Kbd],
  label: [apiReference.Label],
  list: [apiReference.List],
  listbox: [apiReference.Listbox],
  message: [apiReference.Message, apiReference.MessageActions],
  menu: [apiReference.Menu, apiReference.MenuTrigger, apiReference.ContextMenuTrigger],
  'multi-select': [apiReference.MultiSelect],
  navbar: [apiReference.Navbar, apiReference.NavbarBrand, apiReference.NavbarAction, apiReference.NavbarContent],
  'order-list': [apiReference.OrderList],
  pagination: [apiReference.Pagination],
  progress: [apiReference.Progress],
  radio: [apiReference.Radio],
  range: [apiReference.Range],
  select: [apiReference.Select],
  'select-button': [apiReference.SelectButton],
  sidebar: [apiReference.Sidebar, apiReference.SidebarHeader, apiReference.SidebarFooter],
  spinner: [apiReference.Spinner],
  status: [apiReference.Status],
  table: [apiReference.Table],
  tabs: [apiReference.Tabs],
  textarea: [apiReference.Textarea],
  toggle: [apiReference.Toggle],
  'toggle-button': [apiReference.ToggleButton],
};
