import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, relative } from 'node:path';
import type { Options as PrettierOptions } from 'prettier';
import prettier from 'prettier';
import type { ApiReferenceData } from '../../playground/src/app/shared/api-reference/api-reference.types';
import type { ApiReferencePaths } from './generator';

export interface GeneratedApi {
  readonly references: Readonly<Record<string, ApiReferenceData>>;
  readonly referencesByRoute: Readonly<Record<string, readonly string[]>>;
}

const GENERATED_BANNER: string = '/* Generated by tools/generate-api-reference.ts. Do not edit. */';
const API_TYPES_IMPORT: string = "import type { ApiReferenceData } from '../shared/api-reference/api-reference.types';";

// Documentation validation

function findMissingTypeDocumentation(reference: ApiReferenceData): string[] {
  const missing: string[] = [];
  for (const type of reference.types) {
    if (!type.description) missing.push(`${reference.className}.${type.name}`);
    if (type.source !== 'library') continue;

    for (const member of type.members) {
      if (!member.description) missing.push(`${reference.className}.${type.name}.${member.name}`);
    }
  }

  return missing;
}

function findMissingDocumentation(reference: ApiReferenceData): string[] {
  const missing: string[] = [];
  if (!reference.description) missing.push(reference.className);
  for (const member of reference.members) {
    if (!member.description) missing.push(`${reference.className}.${member.name}`);
  }
  for (const template of reference.templates) {
    if (!template.description) missing.push(`${reference.className}.${template.name}`);
  }

  missing.push(...findMissingTypeDocumentation(reference));

  for (const style of reference.styles) {
    if (!style.description) missing.push(`${reference.className}.${style.name}`);
  }

  return missing;
}

function validateDocumentation(data: Readonly<Record<string, ApiReferenceData>>): void {
  const missing: string[] = [];
  for (const reference of Object.values(data)) missing.push(...findMissingDocumentation(reference));

  if (missing.length) throw new Error(`Missing public API documentation: ${missing.join(', ')}`);
}

// Generated TypeScript source

function renderReferenceShape(references: Readonly<Record<string, ApiReferenceData>>): string {
  return Object.keys(references)
    .map((name: string): string => `readonly ${name}: ApiReferenceData;`)
    .join('\n');
}

function renderRoutes(routes: Readonly<Record<string, readonly string[]>>): string {
  const lines: string[] = [];
  const entries: readonly [string, readonly string[]][] = Object.entries(routes).sort(([first], [second]): number =>
    first.localeCompare(second),
  );

  for (const [route, names] of entries) {
    const references: string = names.map((name: string): string => `apiReference.${name}`).join(', ');
    lines.push(`${JSON.stringify(route)}: [${references}],`);
  }

  return lines.join('\n');
}

function renderSource(data: GeneratedApi): string {
  const members: string = renderReferenceShape(data.references);
  const routeEntries: string = renderRoutes(data.referencesByRoute);

  return (
    `${GENERATED_BANNER}\n` +
    `${API_TYPES_IMPORT}\n\n` +
    `export const apiReference: Readonly<{${members}}> = ${JSON.stringify(data.references, null, 2)} as const;\n\n` +
    `export const apiReferences: Readonly<Record<string, readonly ApiReferenceData[]>> = {${routeEntries}};\n`
  );
}

export async function saveGeneratedApi(data: GeneratedApi, paths: ApiReferencePaths): Promise<void> {
  validateDocumentation(data.references);

  const options: PrettierOptions | null = await prettier.resolveConfig(paths.outputFile);
  const formatted: string = await prettier.format(renderSource(data), { ...options, parser: 'typescript' });

  mkdirSync(dirname(paths.outputFile), { recursive: true });
  writeFileSync(paths.outputFile, formatted);

  console.log(
    `Generated ${Object.keys(data.references).length} API references across ${Object.keys(data.referencesByRoute).length} routes in ${relative(paths.root, paths.outputFile)}.`,
  );
}
