import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import type { Options as PrettierOptions } from 'prettier';
import prettier from 'prettier';
import postcss from 'postcss';
import type { AtRule, ChildNode, Comment, Declaration, Root } from 'postcss';

export interface ThemeTokenReference {
  readonly darkValue: string;
  readonly group: string;
  readonly lightValue: string;
  readonly purpose: string;
  readonly token: string;
}

interface ThemeTokenDocumentation {
  readonly group: string;
  readonly purpose: string;
}

const THEME_SOURCE_FILE: string = 'sushi/src/styles/sushi.themes.css';
const GENERATED_FILE: string = 'playground/src/app/generated/theme-token-reference.generated.ts';
const LIGHT_THEME: string = 'sushi';
const DARK_THEME: string = 'sushi-dark';
const TOKEN_DOCUMENTATION_PATTERN: RegExp = /^\*\s*@group\s+([^|]+)\|\s*(.+)$/u;
const GENERATED_BANNER: string = '/* Generated by tools/generate-api-reference.ts. Do not edit. */';

function themeName(rule: AtRule): string | null {
  const declaration: Declaration | undefined = rule.nodes?.find(
    (node: ChildNode): node is Declaration => node.type === 'decl' && node.prop === 'name',
  );

  return declaration?.value.replaceAll(/["']/gu, '') ?? null;
}

function findTheme(stylesheet: Root, name: string): AtRule {
  const theme: AtRule | undefined = stylesheet.nodes.find(
    (node: ChildNode): node is AtRule => node.type === 'atrule' && node.name === 'plugin' && themeName(node) === name,
  );

  if (!theme) throw new Error(`Theme "${name}" was not found.`);
  return theme;
}

function documentedToken(declaration: Declaration): ThemeTokenDocumentation | null {
  const previous: ChildNode | undefined = declaration.prev();
  if (previous?.type !== 'comment') return null;

  const comment: Comment = previous;
  const match: RegExpExecArray | null = TOKEN_DOCUMENTATION_PATTERN.exec(comment.text.trim());
  if (!match?.[1] || !match[2]) return null;

  return { group: match[1].trim(), purpose: match[2].trim() };
}

function valuesFrom(theme: AtRule): ReadonlyMap<string, string> {
  const values: Map<string, string> = new Map<string, string>();
  theme.walkDecls((declaration: Declaration): void => {
    if (declaration.prop.startsWith('--')) values.set(declaration.prop, declaration.value);
  });
  return values;
}

export function readThemeTokenReferences(source: string): readonly ThemeTokenReference[] {
  const stylesheet: Root = postcss.parse(source);
  const lightTheme: AtRule = findTheme(stylesheet, LIGHT_THEME);
  const darkValues: ReadonlyMap<string, string> = valuesFrom(findTheme(stylesheet, DARK_THEME));
  const tokens: ThemeTokenReference[] = [];

  lightTheme.walkDecls((declaration: Declaration): void => {
    const documentation: ThemeTokenDocumentation | null = documentedToken(declaration);
    if (!declaration.prop.startsWith('--')) return;
    if (!documentation) throw new Error(`Theme token "${declaration.prop}" is missing documentation.`);

    const darkValue: string | undefined = darkValues.get(declaration.prop);
    if (!darkValue) throw new Error(`Theme token "${declaration.prop}" is missing from ${DARK_THEME}.`);

    tokens.push({
      token: declaration.prop,
      lightValue: declaration.value,
      darkValue,
      ...documentation,
    });
  });

  return tokens;
}

function renderSource(tokens: readonly ThemeTokenReference[]): string {
  return (
    `${GENERATED_BANNER}\n\n` +
    `export interface ThemeTokenReference {\n` +
    `  readonly darkValue: string;\n` +
    `  readonly group: string;\n` +
    `  readonly lightValue: string;\n` +
    `  readonly purpose: string;\n` +
    `  readonly token: string;\n` +
    `}\n\n` +
    `export const THEME_TOKEN_REFERENCES: readonly ThemeTokenReference[] = ${JSON.stringify(tokens, null, 2)};\n`
  );
}

export async function generateThemeTokenReference(root: string = process.cwd()): Promise<void> {
  const sourceFile: string = join(root, THEME_SOURCE_FILE);
  const outputFile: string = join(root, GENERATED_FILE);
  const tokens: readonly ThemeTokenReference[] = readThemeTokenReferences(readFileSync(sourceFile, 'utf8'));
  const options: PrettierOptions | null = await prettier.resolveConfig(outputFile);
  const formatted: string = await prettier.format(renderSource(tokens), { ...options, parser: 'typescript' });

  writeFileSync(outputFile, formatted);
}
